# Generated by Django 3.0.2 on 2020-01-25 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reactions', '0004_auto_20200125_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='time_of_reaction',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('skills', models.ManyToManyField(blank=True, to='reactions.Skill')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='task',
            field=models.ManyToManyField(blank=True, to='reactions.Task'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reactions.Task'),
            preserve_default=False,
        ),
    ]
