# Generated by Django 3.0.2 on 2020-01-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0006_auto_20200125_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='comment_sentiment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
