# Generated by Django 3.0.2 on 2020-01-26 02:53

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0007_reaction_comment_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='comment_sentiment',
            field=computed_property.fields.ComputedIntegerField(compute_from='calculate_sentiment', editable=False),
        ),
    ]
