# Generated by Django 3.0.2 on 2020-01-26 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0010_profile_user_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_group',
            new_name='user_lvl',
        ),
    ]
